"""empty message

Revision ID: 000e0d6de311
Revises: 
Create Date: 2023-05-09 10:10:36.809039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000e0d6de311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('email', name=op.f('uq_brands_email'))
    )
    op.create_table('influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_influencers')),
    sa.UniqueConstraint('email', name=op.f('uq_influencers_email')),
    sa.UniqueConstraint('instagram', name=op.f('uq_influencers_instagram')),
    sa.UniqueConstraint('twitter', name=op.f('uq_influencers_twitter')),
    sa.UniqueConstraint('youtube', name=op.f('uq_influencers_youtube'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('target_revenue', sa.Integer(), nullable=True),
    sa.Column('target_views', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_campaigns_brand_id_brands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('brand_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_campaigns_brand_id_brands')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_brand_campaigns_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_campaigns'))
    )
    op.create_table('influencer_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_Id', sa.Integer(), nullable=True),
    sa.Column('campaign_Id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_Id'], ['campaigns.id'], name=op.f('fk_influencer_campaigns_campaign_Id_campaigns')),
    sa.ForeignKeyConstraint(['influencer_Id'], ['influencers.id'], name=op.f('fk_influencer_campaigns_influencer_Id_influencers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_influencer_campaigns'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_campaigns')
    op.drop_table('brand_campaigns')
    op.drop_table('campaigns')
    op.drop_table('influencers')
    op.drop_table('brands')
    # ### end Alembic commands ###
